### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by w4zir** [adambielski/CapsNet-pytorch#3]
I have NVIDIA GTX 1060 with 6GB RAM and cpu RAM of 16GB. Getting the following error after 1st epoch:

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "net.py", line 275, in <module>
    test_loss = test()
  File "net.py", line 260, in test
    output, probs = model(data)
  File "/home/khan/anaconda3/envs/kt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "net.py", line 101, in forward
    x = self.digitCaps(x)
  File "/home/khan/anaconda3/envs/kt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "net.py", line 62, in forward
    u_predict = caps_output.matmul(self.weights)
  File "/home/khan/anaconda3/envs/kt/lib/python3.6/site-packages/torch/autograd/variable.py", line 386, in matmul
    return torch.matmul(self, other)
  File "/home/khan/anaconda3/envs/kt/lib/python3.6/site-packages/torch/functional.py", line 219, in matmul
    tensor2_expanded = tensor2.expand(*(expand_batch_portion + tensor2_exp_size[-2:])) \
  File "/home/khan/anaconda3/envs/kt/lib/python3.6/site-packages/torch/autograd/variable.py", line 280, in contiguous
    self.data = self.data.contiguous()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCStorage.cu:58

**Comment by adambielski** [comment]
Hi @w4zir 
Try lowering test batch size, the default is set to a quite high value. You can do it by adding `--test-batch-size 128` to running arguments

**Comment by w4zir** [comment]
It worked. 99% test accuracy after 1 epoch is great.
