### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by raul1968** [adambielski/CapsNet-pytorch#9]
/home/raul/Desktop/CapsNet-pytorch/net.py:28: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = F.softmax(self.b)
/home/raul/Desktop/CapsNet-pytorch/net.py:38: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = F.softmax(b_batch.view(-1, output_caps)).view(-1, input_caps, output_caps, 1)
Traceback (most recent call last):
  File "/home/raul/Desktop/CapsNet-pytorch/net.py", line 275, in <module>
    train(epoch)
  File "/home/raul/Desktop/CapsNet-pytorch/net.py", line 244, in train
    100. * batch_idx / len(train_loader), loss.data[0]))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by luo3300612** [comment]
use loss.item() instead of loss.data[0]

**Comment by adambielski** [comment]
There were some breaking changes in newer PyTorch versions; I used version 0.3.0 when I was writing the code.
